{% set name = "ipyaladin" %}
{% set version = "0.1.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 79dd79fd2c1c13930e5557b9e7706cfdcfd1836724dbfa96ba42d2450552949e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - jupyter-packaging
    - jupyterlab
    - setuptools>=40.8.0
  run:
    - python
    - jupyterlab
    - jupyter
    - ipywidgets>=7.6.0,<9

test:
  imports:
    - ipyaladin

about:
  home: https://github.com/cds-astro/ipyaladin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite
  doc_url: https://aladin.u-strasbg.fr/AladinLite/doc/API/
  dev_url: https://github.com/cds-astro/ipyaladin

extra:
  recipe-maintainers:
    - bmatthieu3
    - tboch

