name: deploy-documentation
on:
  push:
    tags:
      - v*
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout branch ${{ github.head_ref }}"
        uses: actions/checkout@v4
      - name: "Set up Python on Ubuntu"
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: "Build doc"
        run: |
          # Build the doc
          python3 -m pip install --upgrade pip setuptools
          pip install .[docs,recommended]
          sudo apt-get install pandoc
          cd ./docs
          make html
      - name: "Publish doc on github pages (commit on branch gh-pages)"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html/
