name: python-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4
      - name: "Set up Python on Ubuntu"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Python codestyle"
        run: |
          pip install ".[dev]"
          pip install pytest
          pytest .
