name: python-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4
      - name: "Set up Python on Ubuntu"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Pytest"
        run: |
          pip install ".[dev]"
          pytest .
